### ISSUE TITLE
 Sincere inquiry

### ISSUE THREAD

**Issue by anranlovelife** [weifantt/Dish-TS#1]
Thank you for your research results. After reading, I feel like I received a lot of goods, but can you put the code for the entire project?

**Comment by weifantt** [comment]
Soon

**Comment by anranlovelife** [comment]
Thank you endlessly.

**Comment by GuoHaoren** [comment]
Hi, may I know why the loss function in the code is MSE without prior knowledge

**Comment by weifantt** [comment]
The code can be runned and achieve promising results. I will add the prior knowledge loss later.

**Comment by SomeOneIsWLL** [comment]
Hello, may I ask if it is possible to add a loss function that incorporates prior knowledge? I would like to use it in my project.
