### ISSUE TITLE
Can Dish-TS and Nonstationary-Transformers be used together？

### ISSUE THREAD

**Issue by LanZhenFeng** [weifantt/Dish-TS#2]
Hi! Nonstationary-Transformers use a normalization methods before embedding, called Series Stationarization, and de-normalize before outputing model results. Based on my understanding, Dish-TS is also one of normalization methods. So, can they be put together and work? Does using the two together create redundancy in the components?

**Comment by weifantt** [comment]
An interesting perspective. I think the Series Stationarization in NSTransformer is RevIN and NS Attention is to enhance RevIN from lookbacks, such that there's a chance to combine them with our Dish-TS. Feel free to contact me via email if there are more details to discuss.
